definitions:
  videos.ErrorMessage:
    properties:
      errorMessage:
        type: string
    type: object
  videos.GenerateCoverPageBody:
    properties:
      coverPage:
        type: string
      destPath:
        type: string
      endTime:
        type: string
      fadeInDuration:
        type: string
      fontColor:
        type: string
      fontSize:
        type: string
      startTime:
        type: string
      title:
        type: string
      x:
        type: string
      "y":
        type: string
    type: object
  videos.GenerateVideoBody:
    properties:
      bgmMusic:
        type: string
      coverPage:
        type: string
      title:
        type: string
      videoSrcList:
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
paths:
  /videos:
    get:
      consumes:
      - application/json
      description: A GET function which fetch the video generating status, Output
        path should be absolute.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: 'Accespt query params PID: process ID, ip: IP address of the server,
        outputPath: the pre-provided output path for the video'
      tags:
      - video
    post:
      consumes:
      - application/json
      description: A POST function which generates video based on video sources and
        themes (background, cover and music) selected. All params should be absolute
        path
      parameters:
      - description: GenerateVideoBody
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/videos.GenerateVideoBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/videos.ErrorMessage'
      summary: Accept user-provided videos, images and themes, and generate video
        for user to download
      tags:
      - video
  /videos/cover:
    post:
      consumes:
      - application/json
      description: A POST function which generates cover videos based on user input,
        e.g. font, size, styles etc.
      parameters:
      - description: GenerateCoverPageBody
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/videos.GenerateCoverPageBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad requests
          schema:
            type: string
      summary: Generates cover videos based on user input, e.g. font, size, styles
        etc.
      tags:
      - video
swagger: "2.0"
