definitions:
  videos.GenerateCoverPageBody:
    properties:
      coverPage:
        type: string
      destPath:
        type: string
      endTime:
        type: string
      fadeInDuration:
        type: string
      fontColor:
        type: string
      fontSize:
        type: string
      startTime:
        type: string
      title:
        type: string
      x:
        type: string
      "y":
        type: string
    type: object
  videos.GenerateVideoBody:
    properties:
      bgmMusic:
        type: string
      coverPage:
        type: string
      title:
        type: string
      videoSrcList:
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
paths:
  /video:
    post:
      consumes:
      - application/json
      description: A POST function which generates cover videos based on user input,
        e.g. font, size, styles etc.
      parameters:
      - description: GenerateCoverPageBody
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/videos.GenerateCoverPageBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad requests
          schema:
            type: string
      summary: Generates cover videos based on user input, e.g. font, size, styles
        etc.
      tags:
      - video
swagger: "2.0"
